JPIET/urls.py
from django.contrib import admin
from django.urls import path, include
from .import views
from django.conf import settings
# from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static



urlpatterns = [
    
    # path('', views.email_check, name='email_check'),
    
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('fault/<str:fault>', views.fault, name='fault'),
    path('success/<str:success>', views.success, name='success'),
    path('account/', include('account.urls', namespace='account')),
    path('frontend/', include('frontend.urls', namespace='frontend')),
    path('admission/', include('admission.urls', namespace='admission')),
    
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admission/urls.py
from django.urls import path
from . import views

app_name = 'admission'

urlpatterns = [

		path('add-application/', views.add_application, name = 'add_application'),
		path('view-application/', views.view_application, name = 'view_application'),
		path('add-candidate/<int:pk>/', views.add_candidate, name = 'add_candidate'),
		path('view-candidate/<int:pk>/', views.view_candidate, name = 'view_candidate'),
		path('view-application-list/', views.view_application_list, name = 'view_application_list'),
		path('view-application-details/<int:pk>/', views.view_application_details, name = 'view_application_details'),
		path('edit-application/<int:pk>/', views.edit_application, name = 'edit_application'),
		path('delete-application/<int:pk>/', views.delete_application, name = 'delete_application'),
		
		path('view-candidate-application/<int:pk>/', views.view_candidate_application, name = 'view_candidate_application'),
		path('print-candidate-application/<int:pk>/', views.print_candidate_application, name = 'print_candidate_application'),

]

admission/forms.py
from django import forms

from frontend import models as fro_models
from . import models


class ApplicationForm(forms.ModelForm):

    class Meta():
        model = models.Application
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['course_1'].widget.attrs['onfocusout'] = 'choiceSelection(event)'
        self.fields['course_2'].widget.attrs['onfocusout'] = 'choiceSelection(event)'
        self.fields['course_3'].widget.attrs['onfocusout'] = 'choiceSelection(event)'
        self.fields['course_4'].widget.attrs['onfocusout'] = 'choiceSelection(event)'
        self.fields['course_5'].widget.attrs['onfocusout'] = 'choiceSelection(event)'
        self.fields['course_6'].widget.attrs['onfocusout'] = 'choiceSelection(event)'
        self.fields['course_7'].widget.attrs['onfocusout'] = 'choiceSelection(event)'
        self.fields['course_8'].widget.attrs['onfocusout'] = 'choiceSelection(event)'
        self.fields['course_9'].widget.attrs['onfocusout'] = 'choiceSelection(event)'
        self.fields['course_10'].widget.attrs['onfocusout'] = 'choiceSelection(event)'
        self.fields['course_11'].widget.attrs['onfocusout'] = 'choiceSelection(event)'
        self.fields['course_12'].widget.attrs['onfocusout'] = 'choiceSelection(event)'
        self.fields['course_13'].widget.attrs['onfocusout'] = 'choiceSelection(event)'
        self.fields['course_14'].widget.attrs['onfocusout'] = 'choiceSelection(event)'
        self.fields['course_15'].widget.attrs['onfocusout'] = 'choiceSelection(event)'


class EditApplicationForm(forms.Form):

    def __init__(self, pk, *args, **kwargs):
        super(EditApplicationForm, self).__init__(*args, **kwargs)
        application = models.Application.objects.get(pk__exact=pk)
        self.fields['is_active'] = forms.BooleanField(label='Active', initial=application.is_active, required=False)



class CandidateForm(forms.ModelForm):

    class Meta():
        model = models.Candidate
        exclude = ['application', 'application_no']


    def __init__(self, pk, *args, **kwargs):
        super(CandidateForm, self).__init__(*args, **kwargs)
        # self.fields['application'].queryset = models.Application.objects.filter(is_active=True)
        application = models.Application.objects.get(pk__exact=pk)
        self.fields['branch_1'].widget.attrs['onfocusout'] = 'choiceSelection(event)'
        self.fields['branch_2'].widget.attrs['onfocusout'] = 'choiceSelection(event)'
        self.fields['branch_3'].widget.attrs['onfocusout'] = 'choiceSelection(event)'
        self.fields['branch_4'].widget.attrs['onfocusout'] = 'choiceSelection(event)'

        pk_list = []

        for attr, value in vars(application).items():
            if attr[0:6]=='course' and not value == None:
                pk_list.append(value)

        c = 4
        for i in range(4-len(pk_list)):
            del self.fields[f'branch_{c}']
            c = c-1

        if (len(pk_list)<5):
            for i in range(1,len(pk_list)+1):
                self.fields[f'branch_{i}'].queryset = fro_models.Course.objects.filter(pk__in=pk_list)
        else:
            for i in range(1,5):
                self.fields[f'branch_{i}'].queryset = fro_models.Course.objects.filter(pk__in=pk_list)

admission/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail
from frontend import models as fro_models
from django.http import HttpResponse


import os
from io import BytesIO
from reportlab.pdfgen import canvas
from reportlab.lib.utils import ImageReader
from reportlab.pdfbase.pdfmetrics import stringWidth
from reportlab.lib.units import inch
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import Paragraph
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.utils import simpleSplit



from account import models as acc_models
from frontend import models as fro_models

from. import models
from. import forms

# Create your views here.

@login_required
def add_application(request):

	admin_all = [u['user'] for u in acc_models.AdminUser.objects.all().values('user')]
	frontend_all = [u['user'] for u in acc_models.FrontEndUser.objects.all().values('user')]
	if request.user.pk in admin_all or request.user.pk in frontend_all:
		if request.method == 'POST':
			form = forms.ApplicationForm(request.POST, request.FILES)
			if form.is_valid():
				application = form.save()
				pk_string = str(application.pk)
				for i in range(4-len(pk_string)):
					pk_string = '0'+pk_string
				models.ApplicationNumber.objects.create(application=application, application_no=int(str(form.cleaned_data['year'])[-2::]+ pk_string + '00000'))

				return redirect('success', success='Application created successfully')
			else:
				return redirect('fault', fault='Server Error')
		else:

			form = forms.ApplicationForm()
			return render(request, 'admission/add-application.html', {'form':form})

	else:
		return redirect('fault', fault='ACCESS DENIED!')




def view_application(request):

	application_list = models.Application.objects.all().filter(is_active__exact=True)
	return render(request, 'admission/view-application.html', {'application_list':application_list} )



def add_candidate(request, pk):

	if request.method == 'POST':
		form = forms.CandidateForm(data=request.POST, files=request.FILES, pk=pk)
		if form.is_valid():
			try:
				candidate = form.save(commit=False)
				candidate.application = models.Application.objects.get(pk__exact=pk)
				application_no_obj = models.ApplicationNumber.objects.get(application__pk__exact=pk)
				candidate.application_no = application_no_obj.application_no + 1
				application_no_obj.application_no  = application_no_obj.application_no + 1					
				candidate.save()
				application_no_obj.save()
				send_mail("JPIET | Application Registered",f'Dear {candidate.name}, Your application is registered with JPIET. The application number for the same is {candidate.application_no}','jpietuniversity@gmail.com',[candidate.email],fail_silently = True)
			except:
				if form.cleaned_data['aadhar'] in [u['aadhar'] for u in models.Candidate.objects.all().values('aadhar')] :
					return redirect('fault', fault='Entered AADHAR number is already registered')
				else:
					return redirect('fault', fault='Server Error')


			return redirect('success', success='Candidate created successfully')
		else:
			if int(request.POST['aadhar']) in [u['aadhar'] for u in models.Candidate.objects.all().filter(application__pk__exact=request.POST['application']).values('aadhar')] :
				return redirect('fault', fault='Entered AADHAR number is already registered')
			else:
				return redirect('fault', fault='Server Error')
	else:

		form = forms.CandidateForm(pk=pk)
		return render(request, 'admission/add-candidate.html', {'form':form})



def view_candidate(request, pk):

	admin_all = [u['user'] for u in acc_models.AdminUser.objects.all().values('user')]
	frontend_all = [u['user'] for u in acc_models.FrontEndUser.objects.all().values('user')]
	if request.user.pk in admin_all or request.user.pk in frontend_all:
		candidate_list = models.Candidate.objects.all().filter(application__pk__exact=pk)
		return render(request, 'admission/view-candidate.html', {'candidate_list':candidate_list})
	else:
		return redirect('fault', fault='ACCESS DENIED!')


def view_application_list(request):

	application_list = models.Application.objects.all()
	return render(request, 'admission/view-application-list.html', {'application_list':application_list} )


def view_application_details(request ,pk):

	try:
		application = models.Application.objects.get(pk__exact=pk)
		return render(request, 'admission/view-application-details.html', {'application':application})
	except:
		return redirect('fault', fault="Server Error")

@login_required
def edit_application(request, pk):

	admin_all = [u['user'] for u in acc_models.AdminUser.objects.all().values('user')]
	frontend_all = [u['user'] for u in acc_models.FrontEndUser.objects.all().values('user')]
	if request.user.pk in admin_all or request.user.pk in frontend_all:

		if request.method == 'POST':
			form = forms.EditApplicationForm(data=request.POST, files=request.FILES, pk=pk)
			if form.is_valid():
				application = models.Application.objects.get(pk__exact=pk)
				
				application.is_active = form.cleaned_data['is_active']
				try:
					application.save()
				except:
					return redirect('fault', fault='Server Error')
				return redirect('success', success='Application data changed successfully')
		else:
			form = forms.EditApplicationForm(pk=pk)
			return render(request, 'admission/add-application.html', {'form':form})

	else:
		return redirect('fault', fault='ACCESS DENIED!')


@login_required
def delete_application(request, pk):


	admin_all = [u['user'] for u in acc_models.AdminUser.objects.all().values('user')]
	frontend_all = [u['user'] for u in acc_models.FrontEndUser.objects.all().values('user')]
	if request.user.pk in admin_all or request.user.pk in frontend_all:
		try:
			models.Application.objects.get(pk__exact=pk).delete()
			return redirect('admission:view_application_list')
		except:
			return redirect('fault', fault="Some error occured")
	else:
		return redirect('fault', fault='ACCESS DENIED!')
	

@login_required
def view_candidate_application(request, pk):

	admin_all = [u['user'] for u in acc_models.AdminUser.objects.all().values('user')]
	frontend_all = [u['user'] for u in acc_models.FrontEndUser.objects.all().values('user')]
	if request.user.pk in admin_all or request.user.pk in frontend_all:
		try:
			candidate = models.Candidate.objects.get(pk__exact=pk)
		except:
			return redirect('fault', fault='Server Error')
		return render(request, 'admission/view-candidate-application.html', {'candidate':candidate})

	else:
		return redirect('fault', fault='ACCESS DENIED!')






def print_candidate_application(request, pk):

	admin_all = [u['user'] for u in acc_models.AdminUser.objects.all().values('user')]
	frontend_all = [u['user'] for u in acc_models.FrontEndUser.objects.all().values('user')]
	if request.user.pk in admin_all or request.user.pk in frontend_all:
		try:
			candidate = models.Candidate.objects.get(pk__exact=pk)
		except:
			return redirect('fault', fault='Server Error')
		# return render(request, 'admission/view-candidate-application.html', {'candidate':candidate})

		response = HttpResponse(content_type='application/pdf')
		response['Content-Disposition'] = f'attachment; filename="{candidate.application_no}.pdf" '
		buffer = BytesIO()
		p = canvas.Canvas(buffer, bottomup=0)
		width_A4, height_A4 = A4



		p.saveState()
		BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
		temp = fro_models.HomeImage.objects.get(id__exact=1).logo_image.name
		logo_path = os.path.join(BASE_DIR, f'media/{temp}')
		logo = ImageReader(logo_path)
		p.scale(1,-1)
		p.drawImage(logo, inch/3, -inch/3, 100, -100)
		p.restoreState()


		p.setFont("Helvetica", 20)
		org_name = 'JP Institute of Engineering and Technology'
		org_name_width = stringWidth(org_name, "Helvetica", 20)
		p.drawString(((width_A4+100-org_name_width)/2), 50 , org_name)

		p.setFont("Helvetica", 15)
		org_add1 = 'College Code : 282'
		org_add1_width = stringWidth(org_add1, "Helvetica", 15)
		p.drawString(((width_A4+100-org_add1_width)/2), 80 , org_add1)

		p.setLineWidth(1)
		p.line(inch/2, 140, width_A4-inch/2,140)



		p.setFont("Helvetica-Bold", 16)
		heading = f"CANDIDATE APPLICATION"
		heading_width = stringWidth(heading, "Helvetica-Bold", 16)
		p.drawString(((width_A4-heading_width)/2), 180 , heading)

		p.setLineWidth(1)
		p.line(((width_A4-heading_width)/2), 181, ((width_A4-heading_width)/2)+heading_width,181)


		p.setFont("Helvetica-Bold", 12)
		item1_1 = f"Application: "
		p.drawString(inch/2, 220, item1_1)
		p.setFont("Helvetica", 12)
		item1_2 = f"{candidate.application.name}"
		p.drawString((inch/2)+stringWidth(item1_1, "Helvetica-Bold", 12), 220, item1_2)


		p.setFont("Helvetica-Bold", 12)
		item1_1 = f"Application Number: "
		p.drawString(width_A4/2, 220, item1_1)
		p.setFont("Helvetica", 12)
		item1_2 = f"{candidate.application_no}"
		p.drawString((width_A4/2)+stringWidth(item1_1, "Helvetica-Bold", 12), 220, item1_2)


		p.setFont("Helvetica-Bold", 12)
		item2_1 = f"Name: "
		p.drawString(inch/2, 240, item2_1)
		p.setFont("Helvetica", 12)
		item2_2 = f"{candidate.name}"
		p.drawString((inch/2)+stringWidth(item2_1, "Helvetica-Bold", 12), 240, item2_2)


		p.setFont("Helvetica-Bold", 12)
		item2_1 = f"Category: "
		p.drawString(width_A4/2, 240, item2_1)
		p.setFont("Helvetica", 12)
		item2_2 = f"{candidate.category}"
		p.drawString((width_A4/2)+stringWidth(item2_1, "Helvetica-Bold", 12), 240, item2_2)


		p.setFont("Helvetica-Bold", 12)
		item3_1 = f"Father's name: "
		p.drawString(inch/2, 260, item3_1)
		p.setFont("Helvetica", 12)
		item3_2 = f"{candidate.father_name}"
		p.drawString((inch/2)+stringWidth(item3_1, "Helvetica-Bold", 12), 260, item3_2)


		p.setFont("Helvetica-Bold", 12)
		item4_1 = f"Mother's Name: "
		p.drawString(width_A4/2, 260, item4_1)
		p.setFont("Helvetica", 12)
		item4_2 = f"{candidate.mother_name}"

admission/templates/admission/add-candidate.html
{% extends 'base.html' %}
{% block content %}
    <script>
        function choiceSelection(event) {
            if (event.target.id === "id_branch_1") {
                index = event.target.selectedIndex;
                document.getElementById('id_branch_2').options[index].setAttribute("disabled", "");
                document.getElementById('id_branch_3').options[index].setAttribute("disabled", "");
                document.getElementById('id_branch_4').options[index].setAttribute("disabled", "");
            } else if (event.target.id === "id_branch_2") {
                index = event.target.selectedIndex;
                document.getElementById('id_branch_1').options[index].setAttribute("disabled", "");
                document.getElementById('id_branch_3').options[index].setAttribute("disabled", "");
                document.getElementById('id_branch_4').options[index].setAttribute("disabled", "");
            } else if (event.target.id === "id_branch_3") {
                index = event.target.selectedIndex;
                document.getElementById('id_branch_2').options[index].setAttribute("disabled", "");
                document.getElementById('id_branch_1').options[index].setAttribute("disabled", "");
                document.getElementById('id_branch_4').options[index].setAttribute("disabled", "");
            } else if (event.target.id === "id_branch_4") {
                index = event.target.selectedIndex;
                document.getElementById('id_branch_1').options[index].setAttribute("disabled", "");
                document.getElementById('id_branch_2').options[index].setAttribute("disabled", "");
                document.getElementById('id_branch_3').options[index].setAttribute("disabled", "");
            }
            console.log(event.target.selectedIndex, event.target.id);
        }
    </script>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Submit">
    </form>
{% endblock %}

admission/templates/admission/view-application-details.html
{% extends 'base.html' %}
{% block content %}
<br><br>
{{application.name}}
{{application.year}}
{{application.is_active}}
<a href="{{ application.pdf.url }}">Download</a>
{{application.course_1}}
{{application.course_2}}
{{application.course_3}}
{{application.course_4}}
{{application.course_5}}
{{application.course_6}}
{{application.course_7}}
{{application.course_8}}
{{application.course_9}}
{{application.course_10}}
{{application.course_11}}
{{application.course_12}}
{{application.course_13}}
{{application.course_14}}
{{application.course_15}}<br>
<a href="{% url 'admission:edit_application' pk=application.pk %}">Change status</a>
{% endblock %}

admission/templates/admission/view-application-list.html
{% extends 'base.html' %}
{% block content %}
<br><br>
    {% for application in application_list %}
        <a href="{% url 'admission:view_application_details' pk=application.pk %}">{{application.name}} {{application.year}}</a>
        <a href="{% url 'admission:delete_application' pk=application.pk %}">x</a>
        <br>
    {% endfor %}
{% endblock %}

admission/templates/admission/view-application.html
{% extends 'base.html' %}
{% block content %}
<br><br>
    {% for application in application_list %}
        <a href="{% url 'admission:add_candidate' pk=application.pk %}">{{application.name}} {{application.year}}</a>
        <a href="{{ application.pdf.url }}">Download</a>
        {% if user.pk in admin_all or user.pk in frontend_all %}
        	<a href="{% url 'admission:view_candidate' pk=application.pk %}">View Registered Candidates</a>
        {% endif %}


        <br>
    {% endfor %}
{% endblock %}

admission/templates/admission/view-candidate-application.html
{% extends 'base.html' %}
{% block content %}
<br><br>

<a href="{% url 'admission:print_candidate_application' pk=candidate.pk %}"><button>Download</button></a>

<br>
<br>

<strong>Application - </strong>{{ candidate.application.name }} <br>
<strong>Application Number - </strong>{{ candidate.application_no }} <br>
<strong>Name - </strong>{{ candidate.name }} <br>
<strong>Father's Name - </strong>{{ candidate.father_name }} <br>
<strong>Mother's Name - </strong>{{ candidate.mother_name }} <br>
<strong>Date Of Birth - </strong>{{ candidate.dob }} <br>
<strong>AADHAR Number - </strong>{{ candidate.aadhar }} <br>
<strong>Correspondence Address - </strong>{{ candidate.corr_add }} <br>
<strong>Permanent Address - </strong>{{ candidate.perm_add }} <br>
<strong>Category - </strong>{{ candidate.category }} <br>
<strong>Gender - </strong>{{ candidate.gender }} <br>
<strong>Nationality - </strong>{{ candidate.nationality }} <br>
<strong>Email - </strong>{{ candidate.email }} <br>
<strong>Phone number - </strong>{{ candidate.phn }} <br>
<strong>Father's Occupation - </strong>{{ candidate.father_occupation }} <br>
<strong>Father's Income - </strong>{{ candidate.father_income }} <br>
<strong>Class 10th Roll Number  - </strong>{{ candidate.roll_10 }} <br>
<strong>Class 10th Aggregate Score - </strong>{{ candidate.aggregate_10 }} <br>
<strong>Class 10th PCM - </strong>{{ candidate.pcm_10 }} <br>
<strong>Class 12th Roll Number  - </strong>{{ candidate.roll_12 }} <br>
<strong>Class 12th Aggregate Score - </strong>{{ candidate.aggregate_12 }} <br>
<strong>Class 12th PCM - </strong>{{ candidate.pcm_12 }} <br>
<strong>UPSEE Roll number - </strong>{{ candidate.roll_upsee }} <br>
<strong>UPSEE General Rank - </strong>{{ candidate.gen_rank }} <br>
<strong>UPSEE Category Rank - </strong>{{ candidate.cat_rank }} <br>
<strong>Branch Preference 1 - </strong>{{ candidate.branch_1 }} <br>
<strong>Branch Preference 2 - </strong>{{ candidate.branch_2 }} <br>
<strong>Branch Preference 3 - </strong>{{ candidate.branch_3 }} <br>
<strong>Branch Preference 4 - </strong>{{ candidate.branch_4 }} <br>


{% endblock %}

admission/templates/admission/view-candidate.html
{% extends 'base.html' %}
{% block content %}
<br><br>
	<table>
		<thead>
			<tr>
				<th>Application Number</th>
				<th>Name</th>
				<th>UPSEE General Rank</th>
				<th>UPSEE Category Rank</th>
				<th>Branch Preference 1</th>
				<th>Branch Preference 2</th>
				<th>Branch Preference 3</th>
				<th>Branch Preference 4</th>
				<th></th>
			</tr>
		</thead>
		<tbody>
		    {% for candidate in candidate_list %}
		    	<tr>
		    		<td><a href="{% url 'admission:view_candidate_application' pk=candidate.pk %}">{{candidate.application_no}}</a></td>
		    		<td>{{candidate.name}}</td>
		    		<td>{{candidate.gen_rank}}</td>
		    		<td>{{candidate.cat_rank}}</td>
		    		<td>{{candidate.branch_1}}</td>
		    		<td>{{candidate.branch_2}}</td>
		    		<td>{{candidate.branch_3}}</td>
		    		<td>{{candidate.branch_4}}</td>
		    		<td><a href="{% url 'admission:print_candidate_application' pk=candidate.pk %}"><button>Download</button></a></td>
		    	</tr>
		    {% endfor %}
	    </tbody>
    </table>
{% endblock %}