JPIET/urls.py
from django.contrib import admin
from django.urls import path, include
from .import views
from django.conf import settings
# from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static



urlpatterns = [
    
    # path('', views.email_check, name='email_check'),
    
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('fault/<str:fault>', views.fault, name='fault'),
    path('success/<str:success>', views.success, name='success'),
    path('account/', include('account.urls', namespace='account')),
    path('frontend/', include('frontend.urls', namespace='frontend')),
    path('admission/', include('admission.urls', namespace='admission')),
    
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

frontend/urls.py
from django.urls import path
from . import views

app_name = 'frontend'

urlpatterns = [
    path('change-home-image/', views.change_home_image, name='change_home_image'),
    path('change-home-pdf/', views.change_home_pdf, name='change_home_pdf'),
    path('change-stats/', views.change_stats, name='change_stats'),
    path('add-notice/', views.add_notice, name='add_notice'),
    path('view-notices/', views.view_notices, name='view_notices'),
    path('delete-notice/<int:pk>/', views.delete_notice, name='delete_notice'),
    path('edit-notice/<int:pk>/', views.edit_notice, name='edit_notice'),
    path('add-media/', views.add_media, name='add_media'),
    path('view-medias/', views.view_medias, name='view_medias'),
    path('delete-media/<int:pk>/', views.delete_media, name='delete_media'),
    path('add-event/', views.add_event, name='add_event'),
    path('view-events/', views.view_events, name='view_events'),
    path('delete-event/<int:pk>/', views.delete_event, name='delete_event'),
    path('edit-event/<int:pk>/', views.edit_event, name='edit_event'),
    path('add-testimonial/', views.add_testimonial, name='add_testimonial'),
    path('view-testimonials/', views.view_testimonials, name='view_testimonials'),
    path('delete-testimonial/<int:pk>/', views.delete_testimonial, name='delete_testimonial'),
    path('edit-testimonial/<int:pk>/', views.edit_testimonial, name='edit_testimonial'),
    path('add-recruiter/', views.add_recruiter, name='add_recruiter'),
    path('view-recruiters/', views.view_recruiters, name='view_recruiters'),
    path('delete-recruiter/<int:pk>/', views.delete_recruiter, name='delete_recruiter'),
    path('get-about-us/', views.get_about_us, name='get_about_us'),
    path('change-message/<int:uid>/', views.change_message, name='change_message'),
    path('view-about-us/<int:uid>/', views.view_about_us, name='view_about_us'),
    path('add-infrastructure/', views.add_infrastructure, name='add_infrastructure'),
    path('edit-infrastructure/<int:pk>/', views.edit_infrastructure, name='edit_infrastructure'),
    path('delete-infrastructure/<int:pk>/', views.delete_infrastructure, name='delete_infrastructure'),
    path('change-vision-mission/', views.change_vision_mission, name='change_vision_mission'),
    path('add-faculty/', views.add_faculty, name='add_faculty'),
    path('view-faculties/', views.view_faculties, name='view_faculties'),
    path('view-faculty/<int:pk>/', views.view_faculty, name='view_faculty'),
    path('delete-faculty/<int:pk>/', views.delete_faculty, name='delete_faculty'),
    path('edit-faculty/<int:pk>/', views.edit_faculty, name='edit_faculty'),
    path('add-department/', views.add_department, name='add_department'),
    path('add-lab/', views.add_lab, name='add_lab'),
    path('view-labs/', views.view_labs, name='view_labs'),
    path('edit-lab/<int:pk>/', views.edit_lab, name='edit_lab'),
    path('delete-lab/<int:pk>/', views.delete_lab, name='delete_lab'),
    path('view-department-list/', views.view_department_list, name='view_department_list'),
    path('view-department/<int:pk>/', views.view_department, name='view_department'),
    path('edit-department/<int:pk>/', views.edit_department, name='edit_department'),
    path('delete-department/<int:pk>/', views.delete_department, name='delete_department'),
    path('add-training-placement/', views.add_training_placement, name='add_training_placement'),
    path('view-training-placement/', views.view_training_placement, name='view_training_placement'),
    path('edit-training-placement/<int:pk>/', views.edit_training_placement, name='edit_training_placement'),
    path('delete-training-placement/<int:pk>/', views.delete_training_placement, name='delete_training_placement'),
    path('add-course/', views.add_course, name='add_course'),
    path('view-courses/', views.view_courses, name='view_courses'),
    path('edit-course/<int:pk>/', views.edit_course, name='edit_course'),
    path('delete-course/<int:pk>/', views.delete_course, name='delete_course'),
    path('add-syllabus/', views.add_syllabus, name='add_syllabus'),
    path('view-syllabus/', views.view_syllabus, name='view_syllabus'),
    path('edit-syllabus/<int:pk>/', views.edit_syllabus, name='edit_syllabus'),
    path('delete-syllabus/<int:pk>/', views.delete_syllabus, name='delete_syllabus'),
    path('add-exam/', views.add_exam, name='add_exam'),
    path('view-exam/', views.view_exam, name='view_exam'),
    path('edit-exam/<int:pk>/', views.edit_exam, name='edit_exam'),
    path('delete-exam/<int:pk>/', views.delete_exam, name='delete_exam'),



    path('ajax/load-semesters/', views.load_semesters, name='ajax_load_semesters'),
]

frontend/models.py
from django.db import models

# Create your models here.

class HomeImage(models.Model):

	uid = models.PositiveIntegerField(unique=True, blank=False)
	logo_image = models.ImageField(upload_to = 'images/logo', blank=False)
	carousel_image1 = models.ImageField(upload_to = 'images/carousel', blank=False)
	carousel_image2 = models.ImageField(upload_to = 'images/carousel', blank=False)
	carousel_image3 = models.ImageField(upload_to = 'images/carousel', blank=False)
	carousel_image4 = models.ImageField(upload_to = 'images/carousel', blank=False)
	side_image = models.ImageField(upload_to = 'images/side', blank=False)


class Statistics(models.Model):

	uid = models.PositiveIntegerField(blank=False)
	students = models.PositiveIntegerField(blank=False) 
	area = models.PositiveIntegerField(blank=False) 
	alumni = models.PositiveIntegerField(blank=False) 
	recruiters = models.PositiveIntegerField(blank=False) 
	students_placed = models.PositiveIntegerField(blank=False) 
	years = models.PositiveIntegerField(blank=False) 


class Notice(models.Model):

	text = models.TextField(blank=False)
	pdf = models.FileField(upload_to='pdf/notices', blank=False)
	on_landing = models.BooleanField(blank=False)
	created_at = models.DateField(auto_now=True)

	def __str__(self):
		return self.text

	class Meta():

		ordering = ['-pk']


class Media(models.Model):

	pic = models.ImageField(upload_to='images/media_coverage', blank=False)
	on_landing = models.BooleanField(blank=False)

	class Meta():

		ordering = ['-pk']


class Event(models.Model):

	heading = models.CharField(max_length=100, blank=False)
	image = models.ImageField(upload_to='images/event', blank=False)
	details = models.TextField(blank=False)
	on_landing = models.BooleanField(blank=False)

	class Meta():

		ordering = ['-pk']


class Testimonial(models.Model):

	name = models.CharField(max_length=100, blank=False)
	text = models.TextField(blank=False)
	image = models.ImageField(upload_to='images/testimonials', blank=False)

	class Meta():

		ordering = ['-pk']


class Recruiter(models.Model):

	image = models.ImageField(upload_to='images/recruiters', blank=False)
	on_landing = models.BooleanField(blank=False)

	class Meta():

		ordering = ['-pk']



##############ABOUT US#################

class Message(models.Model):

	uid = models.PositiveIntegerField(unique=True, blank=False)
	title = models.CharField(max_length=100, blank=False)
	name = models.CharField(max_length=100, blank=False)
	image = models.ImageField(upload_to='images/message', blank=False)
	message = models.TextField(blank=False)


	def __str__(self):
		return self.title

	class Meta():

		ordering = ['uid']


class Infrastructure(models.Model):

	title = models.CharField(max_length=100, blank=False) 
	image = models.ImageField(upload_to='images/infrastructure', blank=False)
	text = models.TextField(blank=False)

	class Meta():

		ordering = ['pk']

	def __str__(self):
		return self.title


class VisionMission(models.Model):

	uid = models.PositiveIntegerField(unique=True)
	text_above = models.TextField(blank=True)
	bullet1 = models.TextField(blank=True)
	bullet2 = models.TextField(blank=True)
	bullet3 = models.TextField(blank=True)
	bullet4 = models.TextField(blank=True)
	bullet5 = models.TextField(blank=True)
	bullet6 = models.TextField(blank=True)
	bullet7 = models.TextField(blank=True)
	bullet8 = models.TextField(blank=True)
	bullet9 = models.TextField(blank=True)
	bullet10 = models.TextField(blank=True)
	text_below = models.TextField(blank=True)





##################DEPARTMENTS#####################


class Department(models.Model):

	name = models.CharField(max_length=100, blank=False)
	image = models.ImageField(upload_to='images/department', blank=False)
	text = models.TextField(blank=False)

	def __str__(self):
		return self.name
		
	class Meta():

		ordering = ['pk']


class Lab(models.Model):

	department = models.ForeignKey('frontend.Department', related_name='labs', on_delete = models.CASCADE)
	lab = models.CharField(max_length=200, blank=False)


class Faculty(models.Model):

    department = models.ForeignKey('frontend.Department', related_name='faculties', on_delete=models.CASCADE)
    name = models.CharField(max_length=50, blank=False)
    designation = models.CharField(max_length=50, blank=False)
    contact_num = models.PositiveIntegerField(blank=False)
    qualification1 = models.CharField(max_length=50, blank=False)
    qualification2 = models.CharField(max_length=50, blank=True)
    qualification3 = models.CharField(max_length=50, blank=True)
    field_of_interest = models.TextField(blank=False)
    experience = models.TextField(blank=False)
    pic = models.ImageField(upload_to='images/faculty',blank=False)

    class Meta:
        verbose_name_plural = "Faculties"
        ordering = ['pk']

    def __str__(self):
        return self.name


class TrainingPlacement(models.Model):

	heading = models.CharField(max_length=100, blank=False)
	text = models.TextField(blank=False)
	image = models.ImageField(upload_to='images/training_placement', blank=False)

	class Meta():

		ordering = ['-pk']




class Semester(models.Model):

	semester = models.PositiveIntegerField(unique=True)

	def __str__(self):

		return str(self.semester)

	class Meta():

		ordering = ['semester']


class Course(models.Model):

	department = models.ForeignKey('frontend.Department', related_name = 'courses', on_delete = models.CASCADE)
	name = models.CharField(max_length=150, blank=False)
	semesters = models.PositiveIntegerField(blank=False)


	def __str__(self):

		return f'{self.department.name} {self.name}'

	class Meta():
		 ordering = ['pk']


class Syllabus(models.Model):

	course = models.ForeignKey('frontend.Course', related_name='syllabus', on_delete='models.CASCADE')
	# semester = models.PositiveIntegerField(blank=False)
	semester = models.ForeignKey('frontend.Semester', related_name='syllabus', on_delete='models.CASCADE')
	pdf = models.FileField(upload_to='pdf/syllabus', blank=False)

	def __str__(self):

		return f'{self.course} {self.semester}'


class Exam(models.Model):

	course = models.ForeignKey('frontend.Course', related_name='exams', on_delete='models.CASCADE')
	# semester = models.PositiveIntegerField(blank=False)
	semester = models.ForeignKey('frontend.Semester', related_name='exams', on_delete='models.CASCADE')
	date = models.DateField(blank=False)
	pdf = models.FileField(upload_to='pdf/exam', blank=False)

	def __str__(self):

		return f'{self.department.name} {self.name}'


class HomePDF(models.Model):

	uid = models.PositiveIntegerField(unique=True, blank=False)
	information_brochure = models.FileField(upload_to='pdf/home_pdf', blank=False)
	fees = models.FileField(upload_to='pdf/home_pdf', blank=False)
	aicte = models.FileField(upload_to='pdf/home_pdf', blank=False)
	anti_ragging = models.FileField(upload_to='pdf/home_pdf', blank=False)
	training_placement = models.FileField(upload_to='pdf/home_pdf', blank=False)




# class AdmissionApplication(models.Model):

# 	name = models.CharField(max_length=120, blank=False)
# 	father_name = models.CharField(max_length=120, blank=False)
# 	mother_name = models.CharField(max_length=120, blank=False)
# 	dob = models.DateField(blank=False)
# 	aadhar = models.PositiveIntegerField(blank=False)
# 	corr_add = models.TextField(blank=False)
# 	perm_add = models.TextField(blank=False)
# 	gender = models.CharField(max_length=3, choices=(('M','Male'),('F','Female')), blank=False)
# 	nationality = models.CharField(max_length=30, blank=False)
# 	email = models.EmailField(blank=False)
# 	phn = models.PositiveIntegerField(blank=False)
# 	father_occupation = models.CharField(max_length=120, blank=False)
# 	father_income = models.CharField(max_length=100, blank=False)
# 	roll_10 = models.PositiveIntegerField(blank=False)
# 	aggregate_10 = models.CharField(max_length=50, blank=False)
# 	pcm_10 = models.CharField(max_length=50, blank=False)
# 	roll_12 = models.PositiveIntegerField(blank=False)
# 	aggregate_12 = models.CharField(max_length=50, blank=False)
# 	pcm_12 = models.CharField(max_length=50, blank=False)
# 	roll_upsee = models.PositiveIntegerField(blank=False)
# 	gen_rank = models.PositiveIntegerField(blank=False)
# 	cat_rank = models.PositiveIntegerField(blank=False)
# 	branch_1 = models.CharField(max_length=100, blank=False) 
# 	branch_2 = models.CharField(max_length=100, blank=False) 
# 	branch_3 = models.CharField(max_length=100, blank=False) 
# 	branch_4 = models.CharField(max_length=100, blank=False) 

frontend/templates/frontend/add-course.html
{% extends 'base.html' %}
{% block content %}
    <form method="post">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Submit">
    </form>
{% endblock %}

frontend/templates/frontend/add-event.html
{% extends 'base.html' %}
{% block content %}
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Submit">
    </form>
{% endblock %}

frontend/templates/frontend/add-exam.html
{% extends 'base.html' %}
{% block content %}
    <form method="post" enctype="multipart/form-data" id="exam_form" data-semesters-url="{% url 'frontend:ajax_load_semesters' %}" novalidate>
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Submit">
    </form>

    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
	  <script>
	    $("#id_course").change(function () {
	      var url = $("#exam_form").attr("data-semesters-url");  // get the url of the `load_cities` view
	      var courseId = $(this).val();  // get the selected country ID from the HTML input

	      $.ajax({                       // initialize an AJAX request
	        url: url,                    // set the url of the request (= localhost:8000/hr/ajax/load-cities/)
	        data: {
	          'course': courseId       // add the country id to the GET parameters
	        },
	        success: function (data) {   // `data` is the return of the `load_cities` view function
	          $("#id_semester").html(data);  // replace the contents of the city input with the data that came from the server
	        }
	      });

	    });
	  </script>
{% endblock %}

frontend/templates/frontend/add-faculty.html
{% extends 'base.html' %}
{% block content %}
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Submit">
    </form>
{% endblock %}

frontend/templates/frontend/add-infrastructure.html
{% extends 'base.html' %}
{% block content %}
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Submit">
    </form>
{% endblock %}

frontend/templates/frontend/add-media.html
{% extends 'base.html' %}
{% block content %}
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Submit">
    </form>
{% endblock %}

frontend/templates/frontend/add-notice.html
{% extends 'base.html' %}
{% block content %}
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Submit">
    </form>
{% endblock %}

frontend/templates/frontend/add-recruiter.html
{% extends 'base.html' %}
{% block content %}
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Submit">
    </form>
{% endblock %}

frontend/templates/frontend/get_about_us.html
{% extends 'base.html' %}
{% block content %}
	<ol>
		<a href="{% url 'frontend:change_message' uid=1 %}"><li>Overview</li></a>
		<a href="{% url 'frontend:change_message' uid=2 %}"><li>Chairman's Message</li></a>
		<a href="{% url 'frontend:change_message' uid=3 %}"><li>President's Message</li></a>
		<a href="{% url 'frontend:change_message' uid=4 %}"><li>Secretary's Message</li></a>
		<a href="{% url 'frontend:change_message' uid=5 %}"><li>Joint Secretary's Message</li></a>
		<a href="{% url 'frontend:change_message' uid=6 %}"><li>Director's Message</li></a>
	</ol>
{% endblock %}

frontend/templates/frontend/home-image.html
{% extends 'base.html' %}
{% block content %}
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Submit">
    </form>
{% endblock %}

frontend/templates/frontend/view-exam.html
{% extends 'base.html' %}
{% block content %}
<br><br><br>        
    {% for exam in exam_list %}
        <a href="{{exam.pdf.url}}">{{exam.course.department.name}} - {{exam.course.name}} - {{exam.semester}} - {{exam.date}}</a><br>
        {% if user.is_authenticated %}
            {% if user.pk in admin_all or user.pk in frontend_all %}
                <a href="{% url 'frontend:edit_exam' pk=exam.pk %}">Edit</a>
                <a href="{% url 'frontend:delete_exam' pk=exam.pk %}">x</a>
            {% endif %}
        {% endif %}
    {% endfor %}
{% endblock %}

frontend/templates/frontend/view-faculties.html
{% extends 'base.html' %}
{% block content %}
    {% for faculty in faculties %}<br>
        {{faculty.department}}<br>
        {{faculty.name}}<br>
        <img src="{{faculty.pic.url}}" alt="Faculty Image" height="100" width="100"><br>
        {{faculty.designation}}<br>
        {{faculty.contact_num}}<br>
        {{faculty.qualification1}}<br>
        {{faculty.qualification2}}<br>
        {{faculty.qualification3}}<br>
        {{faculty.field_of_interest}}<br>
        {{faculty.experience}}
        <a href="{% url 'frontend:delete_faculty' pk=faculty.pk %}">x</a>
        <a href="{% url 'frontend:edit_faculty' pk=faculty.pk %}">Edit</a>
        <br>
    {% endfor %}
{% endblock %}

frontend/templates/frontend/view-recruiters.html
{% extends 'base.html' %}
{% block content %}
<br>
    {% if user.is_authenticated %}
    {% if user.pk in admin_all or user.pk in frontend_all %}
        {% for recruiter in recruiters %}
        <img src="{{ recruiter.image.url }}" height="100" width="100"> <a href="{% url 'frontend:delete_recruiter' pk=recruiter.pk %}">x</a> <br>
        {% endfor %}
    {% endif %}
    {% endif %}
    {% if not user.is_authenticated %}
    {% for recruiter in recruiters %}
    <img src="{{ recruiter.image.url }}" height="100" width="100"><br>
    {% endfor %}
    {% endif %}
{% endblock %}

frontend/templates/frontend/view-syllabus.html
{% extends 'base.html' %}
{% block content %}
<br><br><br>        
    {% for syllabus in syllabus_list %}
    <br><br>
        <a href="{{syllabus.pdf.url}}">{{syllabus.course.department.name}} - {{syllabus.course.name}} - {{syllabus.semester}}</a>
        {% if user.is_authenticated %}
            {% if user.pk in admin_all or user.pk in frontend_all %}
                <a href="{% url 'frontend:edit_syllabus' pk=syllabus.pk %}">Edit</a>
                <a href="{% url 'frontend:delete_syllabus' pk=syllabus.pk %}">x</a>
            {% endif %}
        {% endif %}
    {% endfor %}
{% endblock %}