JPIET/urls.py
from django.contrib import admin
from django.urls import path, include
from .import views
from django.conf import settings
# from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static



urlpatterns = [
    
    # path('', views.email_check, name='email_check'),
    
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('fault/<str:fault>', views.fault, name='fault'),
    path('success/<str:success>', views.success, name='success'),
    path('account/', include('account.urls', namespace='account')),
    path('frontend/', include('frontend.urls', namespace='frontend')),
    path('admission/', include('admission.urls', namespace='admission')),
    
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path
from . import views

app_name = 'account'

urlpatterns = [
    path("login/", auth_views.LoginView.as_view(template_name='account/login.html'), name="login"),
    path('logout/',auth_views.LogoutView.as_view(),name = 'logout'),
    path('signup/',views.signup, name = 'signup'),
    path('user-list/',views.user_list, name = 'user_list'),
    path('delete-user/<int:pk>/',views.delete_user, name = 'delete_user'),
]

admission/urls.py
from django.urls import path
from . import views

app_name = 'admission'

urlpatterns = [

		path('add-application/', views.add_application, name = 'add_application'),
		path('view-application/', views.view_application, name = 'view_application'),
		path('add-candidate/<int:pk>/', views.add_candidate, name = 'add_candidate'),
		path('view-candidate/<int:pk>/', views.view_candidate, name = 'view_candidate'),
		path('view-application-list/', views.view_application_list, name = 'view_application_list'),
		path('view-application-details/<int:pk>/', views.view_application_details, name = 'view_application_details'),
		path('edit-application/<int:pk>/', views.edit_application, name = 'edit_application'),
		path('delete-application/<int:pk>/', views.delete_application, name = 'delete_application'),
		
		path('view-candidate-application/<int:pk>/', views.view_candidate_application, name = 'view_candidate_application'),
		path('print-candidate-application/<int:pk>/', views.print_candidate_application, name = 'print_candidate_application'),

]

frontend/urls.py
from django.urls import path
from . import views

app_name = 'frontend'

urlpatterns = [
    path('change-home-image/', views.change_home_image, name='change_home_image'),
    path('change-home-pdf/', views.change_home_pdf, name='change_home_pdf'),
    path('change-stats/', views.change_stats, name='change_stats'),
    path('add-notice/', views.add_notice, name='add_notice'),
    path('view-notices/', views.view_notices, name='view_notices'),
    path('delete-notice/<int:pk>/', views.delete_notice, name='delete_notice'),
    path('edit-notice/<int:pk>/', views.edit_notice, name='edit_notice'),
    path('add-media/', views.add_media, name='add_media'),
    path('view-medias/', views.view_medias, name='view_medias'),
    path('delete-media/<int:pk>/', views.delete_media, name='delete_media'),
    path('add-event/', views.add_event, name='add_event'),
    path('view-events/', views.view_events, name='view_events'),
    path('delete-event/<int:pk>/', views.delete_event, name='delete_event'),
    path('edit-event/<int:pk>/', views.edit_event, name='edit_event'),
    path('add-testimonial/', views.add_testimonial, name='add_testimonial'),
    path('view-testimonials/', views.view_testimonials, name='view_testimonials'),
    path('delete-testimonial/<int:pk>/', views.delete_testimonial, name='delete_testimonial'),
    path('edit-testimonial/<int:pk>/', views.edit_testimonial, name='edit_testimonial'),
    path('add-recruiter/', views.add_recruiter, name='add_recruiter'),
    path('view-recruiters/', views.view_recruiters, name='view_recruiters'),
    path('delete-recruiter/<int:pk>/', views.delete_recruiter, name='delete_recruiter'),
    path('get-about-us/', views.get_about_us, name='get_about_us'),
    path('change-message/<int:uid>/', views.change_message, name='change_message'),
    path('view-about-us/<int:uid>/', views.view_about_us, name='view_about_us'),
    path('add-infrastructure/', views.add_infrastructure, name='add_infrastructure'),
    path('edit-infrastructure/<int:pk>/', views.edit_infrastructure, name='edit_infrastructure'),
    path('delete-infrastructure/<int:pk>/', views.delete_infrastructure, name='delete_infrastructure'),
    path('change-vision-mission/', views.change_vision_mission, name='change_vision_mission'),
    path('add-faculty/', views.add_faculty, name='add_faculty'),
    path('view-faculties/', views.view_faculties, name='view_faculties'),
    path('view-faculty/<int:pk>/', views.view_faculty, name='view_faculty'),
    path('delete-faculty/<int:pk>/', views.delete_faculty, name='delete_faculty'),
    path('edit-faculty/<int:pk>/', views.edit_faculty, name='edit_faculty'),
    path('add-department/', views.add_department, name='add_department'),
    path('add-lab/', views.add_lab, name='add_lab'),
    path('view-labs/', views.view_labs, name='view_labs'),
    path('edit-lab/<int:pk>/', views.edit_lab, name='edit_lab'),
    path('delete-lab/<int:pk>/', views.delete_lab, name='delete_lab'),
    path('view-department-list/', views.view_department_list, name='view_department_list'),
    path('view-department/<int:pk>/', views.view_department, name='view_department'),
    path('edit-department/<int:pk>/', views.edit_department, name='edit_department'),
    path('delete-department/<int:pk>/', views.delete_department, name='delete_department'),
    path('add-training-placement/', views.add_training_placement, name='add_training_placement'),
    path('view-training-placement/', views.view_training_placement, name='view_training_placement'),
    path('edit-training-placement/<int:pk>/', views.edit_training_placement, name='edit_training_placement'),
    path('delete-training-placement/<int:pk>/', views.delete_training_placement, name='delete_training_placement'),
    path('add-course/', views.add_course, name='add_course'),
    path('view-courses/', views.view_courses, name='view_courses'),
    path('edit-course/<int:pk>/', views.edit_course, name='edit_course'),
    path('delete-course/<int:pk>/', views.delete_course, name='delete_course'),
    path('add-syllabus/', views.add_syllabus, name='add_syllabus'),
    path('view-syllabus/', views.view_syllabus, name='view_syllabus'),
    path('edit-syllabus/<int:pk>/', views.edit_syllabus, name='edit_syllabus'),
    path('delete-syllabus/<int:pk>/', views.delete_syllabus, name='delete_syllabus'),
    path('add-exam/', views.add_exam, name='add_exam'),
    path('view-exam/', views.view_exam, name='view_exam'),
    path('edit-exam/<int:pk>/', views.edit_exam, name='edit_exam'),
    path('delete-exam/<int:pk>/', views.delete_exam, name='delete_exam'),



    path('ajax/load-semesters/', views.load_semesters, name='ajax_load_semesters'),
]

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>JPIET</title>
    {% block head %}
    {% endblock %}
</head>
<body>
    <a href="{% url 'home' %}">Home</a>
    <br>
    <a href="{% url 'frontend:view_about_us' uid=1 %}">About Us</a>
    <a href="{% url 'frontend:view_about_us' uid=1 %}">Overview</a>
    <a href="{% url 'frontend:view_about_us' uid=2 %}">Chairman's Message</a>
    <a href="{% url 'frontend:view_about_us' uid=3 %}">President's Message</a>
    <a href="{% url 'frontend:view_about_us' uid=4 %}">Secretary's Message</a>
    <a href="{% url 'frontend:view_about_us' uid=5 %}">Joint Secretary's Message</a>
    <a href="{% url 'frontend:view_about_us' uid=6 %}">Director's Message</a>
    <a href="{% url 'frontend:view_about_us' uid=8 %}">Infrastructure</a>
    <a href="{% url 'frontend:view_about_us' uid=7 %}">Vision and Mission</a>
    <br>
    <a href="{% url 'frontend:view_recruiters' %}">Recruiters</a>
    <a href="{% url 'frontend:view_testimonials' %}">Testimonials</a>
    <a href="{% url 'frontend:view_events' %}">Events</a>
    <a href="{% url 'frontend:view_notices' %}">Notices</a>
    <a href="{% url 'frontend:view_medias' %}">Media</a>
    <a href="{% url 'frontend:view_department_list' %}">Departments</a>
    <a href="{% url 'frontend:view_training_placement' %}">Training & Placement</a>
    <a href="{% url 'frontend:view_courses' %}">Courses</a>
    <a href="{% url 'frontend:view_syllabus' %}">Syllabus</a>
    <a href="{% url 'frontend:view_exam' %}">Exam Date Sheet</a>

    {% if user.is_authenticated %}
        <a href="{% url 'account:logout' %}">Logout</a>
        {% if user.pk in admin_all %}
            <br>
            <a href="{% url 'account:signup' %}">Add User</a>
            <a href="{% url 'account:user_list' %}">View Users</a>
            <br>
            <a href="{% url 'frontend:change_home_image' %}">Change home images</a>
            <a href="{% url 'frontend:change_home_pdf' %}">Change home PDFs</a>
            <a href="{% url 'frontend:change_stats' %}">Change Statistics</a>
            <a href="{% url 'frontend:add_notice' %}">Add Notice</a>
            <a href="{% url 'frontend:add_media' %}">Add Media Coverage</a>
            <a href="{% url 'frontend:add_event' %}">Add Event</a>
            <a href="{% url 'frontend:add_testimonial' %}">Add Testimonial</a>
            <a href="{% url 'frontend:add_recruiter' %}">Add Recruiter</a>
            <br>
            <a href="{% url 'frontend:add_department' %}">Add Department</a>
            <a href="{% url 'frontend:add_faculty' %}">Add Faculty</a>
            <a href="{% url 'frontend:add_lab' %}">Add Lab</a>
            <a href="{% url 'frontend:add_course' %}">Add Course</a>
            <a href="{% url 'frontend:add_syllabus' %}">Add Syllabus</a>
            <a href="{% url 'frontend:add_exam' %}">Add Exam Date Sheet</a>
            <br>
            <a href="{% url 'frontend:get_about_us' %}">Change Messages</a>
            <a href="{% url 'frontend:add_infrastructure' %}">Add Infrastructure</a>
            <a href="{% url 'frontend:change_vision_mission' %}">Change Vision & Mission</a>
            <br>
            <a href="{% url 'frontend:add_training_placement' %}">Add Training & Placement</a>
            <br>
            <a href="{% url 'admission:add_application' %}">Add Application</a>
            <a href="{% url 'admission:view_application' %}">View Admission Applications</a>
            <a href="{% url 'admission:view_application_list' %}" >Applications</a>


        {% endif %}
        {% if user.pk in frontend_all %}
            <br>
            <a href="{% url 'frontend:change_home_image' %}">Change home images</a>
            <a href="{% url 'frontend:change_home_pdf' %}">Change home PDFs</a>
            <a href="{% url 'frontend:change_stats' %}">Change Statistics</a>
            <a href="{% url 'frontend:add_notice' %}">Add Notice</a>
            <a href="{% url 'frontend:add_media' %}">Add Media Coverage</a>
            <a href="{% url 'frontend:add_event' %}">Add Event</a>
            <a href="{% url 'frontend:add_testimonial' %}">Add Testimonial</a>
            <a href="{% url 'frontend:add_recruiter' %}">Add Recruiter</a>
            <br>
            <a href="{% url 'frontend:add_department' %}">Add Department</a>
            <a href="{% url 'frontend:add_faculty' %}">Add Faculty</a>
            <a href="{% url 'frontend:add_lab' %}">Add Lab</a>
            <a href="{% url 'frontend:add_course' %}">Add Course</a>
            <a href="{% url 'frontend:add_syllabus' %}">Add Syllabus</a>
            <br>
            <a href="{% url 'frontend:get_about_us' %}">Change Messages</a>
            <a href="{% url 'frontend:add_infrastructure' %}">Add Infrastructure</a>
            <a href="{% url 'frontend:change_vision_mission' %}">Change Vision & Mission</a>
            <br>
            <a href="{% url 'frontend:add_training_placement' %}">Add Training & Placement</a>
            <br>
            <a href="{% url 'admission:add_application' %}">Add Application</a>
            <a href="{% url 'admission:view_application' %}">View Admission Applications</a>

        {% endif %}
        

    {% endif %}
    {% if not user.is_authenticated %}
        <a href="{% url 'admission:view_application' %}">Fill Admission Form</a>
        <a href="{% url 'account:login' %}">Login</a>
    {% endif %}
    {% block content %}
    {% endblock %}
</body>
</html>

templates/fault.html
{% extends 'base.html' %}
{% block content %}
    <h1>{{fault}}</h1>
{% endblock %}

templates/home.html
{% extends 'base.html' %}
{% load counter %}
{% block content %}
    <h1>Home Page</h1>
    <img src="{{ home_image.logo_image.url }}" height="100" width="100"><br>
    <img src="{{ home_image.carousel_image1.url }}" height="100" width="100">
    <img src="{{ home_image.carousel_image2.url }}" height="100" width="100">
    <img src="{{ home_image.carousel_image3.url }}" height="100" width="100">
    <img src="{{ home_image.carousel_image4.url }}" height="100" width="100"><br>
    <img src="{{ home_image.side_image.url }}" height="100" width="100">
    <br><br><br>
    <a href="{{ home_pdf.information_brochure.url }}">Information Brochure</a><br>
    <a href="{{ home_pdf.fees.url }}">Fees</a><br>
    <a href="{{ home_pdf.aicte.url }}">AICTE Approval</a><br>
    <a href="{{ home_pdf.anti_ragging.url }}">Anti-Ragging</a><br>
    <a href="{{ home_pdf.training_placement.url }}">Training & Placement</a><br>
    <br><br><br>
    <h3>About Us</h3>
    <p>{{about_us.message|truncatechars:500}} <a href="{% url 'frontend:view_about_us' uid=1 %}">Read More</a></p>
    <br><br><br>
    <h3>Statistics</h3>
    Students: {{stats.students}}<br>
    Area: {{stats.area}} sq. mt.<br>
    Alumni: {{stats.alumni}}<br>
    Recruiters: {{stats.recruiters}}<br>
    Students Placed: {{stats.students_placed}}<br>
    Years of Excellency: {{stats.years}}<br>
    <br><br><br>
    <h3>Notices</h3>
    {% for notice in notices %}
        {% if forloop.counter|count4 %}
            <a href="{{ notice.pdf.url }}">{{ notice.text }}</a>
        {% endif %}
    {% endfor %}
    <br><br><br>
    <h3>Media Coverage</h3>
    {% for media in medias %}
        {% if forloop.counter|count4 %}
            <img src="{{ media.pic.url }}" height="100" width="100">
        {% endif %}
    {% endfor %}
    <br><br><br>
    <h3>Events</h3>
    {% for event in events %}
        {% if forloop.counter|count4 %}
            <h4>{{event.heading}}</h4>
            <img src="{{ event.image.url }}" height="100" width="100">
            <p>{{event.details}}</p>
        {% endif %}
    {% endfor %}
    <br><br><br>
    <h3>Testimonials</h3>
    {% for testimonial in testimonials %}
        {% if forloop.counter|count4 %}
            <h4>{{testimonial.name}}</h4>
            <img src="{{ testimonial.image.url }}" height="100" width="100">
            <p>{{testimonial.text}}</p>
        {% endif %}
    {% endfor %}
    <br><br><br>
    <h3>Recruiters</h3>
    {% for recruiter in recruiters %}
        {% if forloop.counter|count4 %}
            <img src="{{ recruiter.image.url }}" height="100" width="100">
        {% endif %}
    {% endfor %}
{% endblock %}

templates/success.html
{% extends 'base.html' %}
{% block content %}
    <h1>{{success}}</h1>
{% endblock %}